id: P87C703CB
initial_creation_type: input
source_metadata:
  title: Lungta Series
  language: en
  description: 'Texts on the theme of Lungta (rlung rta/klung rta) or Windhorse, including
    chants to accompany the raising of prayer flags:'
  volume:
    7dc36a882d604e1fa70624b8b34046d3:
      title: Windhorse Practice of Tārā
      parent: Prayers
    4dd01f8b9a12435e9fceff4119039f92:
      title: Raising the Windhorse
      parent: Prayers
    5b550b556c30481ca4fbff9e70d72c12:
      title: Prayer to Gyaltsen Tsemö Pung Gyen
      parent: Prayers
    cfc8e8697ef841c3b9ebcb641ca52fe3:
      title: Brief Gesar Windhorse Invocation
      parent: Prayers
    bf4c1613328c408abbfc33d7e0d413d0:
      title: Brief Windhorse Invocation
      parent: Prayers
    d2b4cff548394efc9a8251b548035ba0:
      title: Daily Lungta Recitation
      parent: Prayers
    ddd835d7cf434b0cbacfada039a04d32:
      title: Short Windhorse Prayer to Gesar
      parent: Prayers
    a56e55fa00174c5cb199537209609b6b:
      title: The Swift Fulfilment of All Wishes—Offering the Flag of Windhorse
      parent: Prayers
    06dbf79fbd024dc1a74accf6d4e90bee:
      title: Brief Windhorse Practice of Tārā
      parent: Prayers
created_at: '2022-03-01T04:29:20.279534'
last_modified_at: '2022-03-01T04:29:20.279540'
